---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:20.04
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        username: root

verifier:
  name: testinfra
