---
- name: Prepare
  hosts: all
  gather_facts: true

  tasks:
    - name: create user
      user:
        name: testuser
        state: present
      become: yes

    - name: Create user dir
      file:
        name: /home/testuser
        state: directory
      become: yes
      
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present
      become: yes
      
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      become: yes
      
    - name: Add sudoers users to wheel group
      user: 
        name: testuser 
        groups: wheel 
        append: yes 
        state: present 
        createhome: yes
      become: yes
    
    - name: "Include dotfiles"
      include_role:
        name: "dotfiles"